In [1]:
from lisa.utils import *
from lisa.library import *
import lisa.models
import numpy as np, pandas as pd, datetime, pytz

In [4]:
dataset = DataSet.objects.get(id=6)

In [5]:
df = dataset.dataframe
df_res = pd.DataFrame(index=df.index, columns=df.columns)

In [6]:
df_mean = df.mean(axis=1)
df_std = df.std(axis=1)

In [7]:
df_quantile_25 = df.quantile(0.25, axis=1)
df_quantile_75 = df.quantile(0.75, axis=1)

In [8]:
count=0
for index, row in df.iterrows():
    for column in df.columns:
        IQR = df_quantile_75[index] - df_quantile_25[index]
        
        if row[column] < (df_quantile_25[index] - (1.5 * IQR)) or row[column] > (df_quantile_75[index] + (1.5 * IQR)):
            df_res.loc[index, column] = 1
            count+=1
            #print(index)
            #print('Val:', np.abs(row[column]))
            #print('Mean:', df_mean[index])
            #print('2 Std:', 2*df_std[index])
print(count)
print(df_res.sum(axis=0))

287
station
23      9.0
24     13.0
25     13.0
26      NaN
27     70.0
28      NaN
29     34.0
30      NaN
31      NaN
32      NaN
33      NaN
34      NaN
35    148.0
37      NaN
dtype: float64

In [24]:
indexes = []
for index, row in df_res.iterrows():
    for column in df_res.columns:
        if row[column] == 1:
            indexes.append(index)
            break

[Timestamp('2017-06-07 01:40:00+0000', tz='UTC'), Timestamp('2017-06-07 01:50:00+0000', tz='UTC'), Timestamp('2017-06-07 02:00:00+0000', tz='UTC'), Timestamp('2017-06-07 02:10:00+0000', tz='UTC'), Timestamp('2017-06-07 02:20:00+0000', tz='UTC'), Timestamp('2017-06-07 02:30:00+0000', tz='UTC'), Timestamp('2017-06-07 02:40:00+0000', tz='UTC'), Timestamp('2017-06-07 02:50:00+0000', tz='UTC'), Timestamp('2017-06-07 03:00:00+0000', tz='UTC'), Timestamp('2017-06-07 03:10:00+0000', tz='UTC'), Timestamp('2017-06-07 03:20:00+0000', tz='UTC'), Timestamp('2017-06-07 03:30:00+0000', tz='UTC'), Timestamp('2017-06-07 03:40:00+0000', tz='UTC'), Timestamp('2017-06-07 03:50:00+0000', tz='UTC'), Timestamp('2017-06-07 04:00:00+0000', tz='UTC'), Timestamp('2017-06-07 04:10:00+0000', tz='UTC'), Timestamp('2017-06-07 04:20:00+0000', tz='UTC'), Timestamp('2017-06-07 04:30:00+0000', tz='UTC'), Timestamp('2017-06-07 04:40:00+0000', tz='UTC'), Timestamp('2017-06-07 04:50:00+0000', tz='UTC'), Timestamp('2017-06-07 05:00:00+0000', tz='UTC'), Timestamp('2017-06-07 05:10:00+0000', tz='UTC'), Timestamp('2017-06-07 05:20:00+0000', tz='UTC'), Timestamp('2017-06-07 05:30:00+0000', tz='UTC'), Timestamp('2017-06-07 05:40:00+0000', tz='UTC'), Timestamp('2017-06-07 05:50:00+0000', tz='UTC'), Timestamp('2017-06-07 06:00:00+0000', tz='UTC'), Timestamp('2017-06-07 06:10:00+0000', tz='UTC'), Timestamp('2017-06-07 06:20:00+0000', tz='UTC'), Timestamp('2017-06-07 06:30:00+0000', tz='UTC'), Timestamp('2017-06-07 06:40:00+0000', tz='UTC'), Timestamp('2017-06-07 06:50:00+0000', tz='UTC'), Timestamp('2017-06-07 07:00:00+0000', tz='UTC'), Timestamp('2017-06-07 07:10:00+0000', tz='UTC'), Timestamp('2017-06-07 18:10:00+0000', tz='UTC'), Timestamp('2017-06-07 18:20:00+0000', tz='UTC'), Timestamp('2017-06-07 18:30:00+0000', tz='UTC'), Timestamp('2017-06-07 18:40:00+0000', tz='UTC'), Timestamp('2017-06-07 18:50:00+0000', tz='UTC'), Timestamp('2017-06-07 19:00:00+0000', tz='UTC'), Timestamp('2017-06-07 19:10:00+0000', tz='UTC'), Timestamp('2017-06-07 19:20:00+0000', tz='UTC'), Timestamp('2017-06-07 19:30:00+0000', tz='UTC'), Timestamp('2017-06-07 19:40:00+0000', tz='UTC'), Timestamp('2017-06-07 19:50:00+0000', tz='UTC'), Timestamp('2017-06-07 20:00:00+0000', tz='UTC'), Timestamp('2017-06-07 20:10:00+0000', tz='UTC'), Timestamp('2017-06-07 20:20:00+0000', tz='UTC'), Timestamp('2017-06-07 20:30:00+0000', tz='UTC'), Timestamp('2017-06-07 20:40:00+0000', tz='UTC'), Timestamp('2017-06-07 20:50:00+0000', tz='UTC'), Timestamp('2017-06-07 21:00:00+0000', tz='UTC'), Timestamp('2017-06-07 21:10:00+0000', tz='UTC'), Timestamp('2017-06-07 21:20:00+0000', tz='UTC'), Timestamp('2017-06-07 21:30:00+0000', tz='UTC'), Timestamp('2017-06-07 21:40:00+0000', tz='UTC'), Timestamp('2017-06-07 21:50:00+0000', tz='UTC'), Timestamp('2017-06-07 22:00:00+0000', tz='UTC'), Timestamp('2017-06-07 22:10:00+0000', tz='UTC'), Timestamp('2017-06-07 22:20:00+0000', tz='UTC'), Timestamp('2017-06-07 22:30:00+0000', tz='UTC'), Timestamp('2017-06-07 22:40:00+0000', tz='UTC'), Timestamp('2017-06-09 00:20:00+0000', tz='UTC'), Timestamp('2017-06-09 00:30:00+0000', tz='UTC'), Timestamp('2017-06-09 01:40:00+0000', tz='UTC'), Timestamp('2017-06-09 02:10:00+0000', tz='UTC'), Timestamp('2017-06-09 02:30:00+0000', tz='UTC'), Timestamp('2017-06-09 02:50:00+0000', tz='UTC'), Timestamp('2017-06-09 03:10:00+0000', tz='UTC'), Timestamp('2017-06-09 03:30:00+0000', tz='UTC'), Timestamp('2017-06-09 03:40:00+0000', tz='UTC'), Timestamp('2017-06-09 03:50:00+0000', tz='UTC'), Timestamp('2017-06-09 04:00:00+0000', tz='UTC'), Timestamp('2017-06-09 04:10:00+0000', tz='UTC'), Timestamp('2017-06-09 04:30:00+0000', tz='UTC'), Timestamp('2017-06-09 04:40:00+0000', tz='UTC'), Timestamp('2017-06-09 04:50:00+0000', tz='UTC'), Timestamp('2017-06-09 05:00:00+0000', tz='UTC'), Timestamp('2017-06-09 05:10:00+0000', tz='UTC'), Timestamp('2017-06-09 05:20:00+0000', tz='UTC'), Timestamp('2017-06-09 05:30:00+0000', tz='UTC'), Timestamp('2017-06-09 05:40:00+0000', tz='UTC'), Timestamp('2017-06-09 05:50:00+0000', tz='UTC'), Timestamp('2017-06-09 06:00:00+0000', tz='UTC'), Timestamp('2017-06-09 06:10:00+0000', tz='UTC'), Timestamp('2017-06-09 10:00:00+0000', tz='UTC'), Timestamp('2017-06-09 10:10:00+0000', tz='UTC'), Timestamp('2017-06-09 10:20:00+0000', tz='UTC'), Timestamp('2017-06-09 10:30:00+0000', tz='UTC'), Timestamp('2017-06-09 10:40:00+0000', tz='UTC'), Timestamp('2017-06-09 10:50:00+0000', tz='UTC'), Timestamp('2017-06-09 11:00:00+0000', tz='UTC'), Timestamp('2017-06-09 11:10:00+0000', tz='UTC'), Timestamp('2017-06-09 11:20:00+0000', tz='UTC'), Timestamp('2017-06-09 11:30:00+0000', tz='UTC'), Timestamp('2017-06-09 18:00:00+0000', tz='UTC'), Timestamp('2017-06-09 18:10:00+0000', tz='UTC'), Timestamp('2017-06-09 18:20:00+0000', tz='UTC'), Timestamp('2017-06-09 18:30:00+0000', tz='UTC'), Timestamp('2017-06-09 18:40:00+0000', tz='UTC'), Timestamp('2017-06-09 18:50:00+0000', tz='UTC'), Timestamp('2017-06-09 19:00:00+0000', tz='UTC'), Timestamp('2017-06-09 19:10:00+0000', tz='UTC'), Timestamp('2017-06-09 19:20:00+0000', tz='UTC'), Timestamp('2017-06-09 19:30:00+0000', tz='UTC'), Timestamp('2017-06-09 19:40:00+0000', tz='UTC'), Timestamp('2017-06-09 19:50:00+0000', tz='UTC'), Timestamp('2017-06-09 20:00:00+0000', tz='UTC'), Timestamp('2017-06-09 20:10:00+0000', tz='UTC'), Timestamp('2017-06-09 20:20:00+0000', tz='UTC'), Timestamp('2017-06-09 20:30:00+0000', tz='UTC'), Timestamp('2017-06-09 20:40:00+0000', tz='UTC'), Timestamp('2017-06-09 20:50:00+0000', tz='UTC'), Timestamp('2017-06-09 21:00:00+0000', tz='UTC'), Timestamp('2017-06-09 21:10:00+0000', tz='UTC'), Timestamp('2017-06-09 21:20:00+0000', tz='UTC'), Timestamp('2017-06-09 21:30:00+0000', tz='UTC'), Timestamp('2017-06-09 21:40:00+0000', tz='UTC'), Timestamp('2017-06-09 21:50:00+0000', tz='UTC'), Timestamp('2017-06-09 22:00:00+0000', tz='UTC'), Timestamp('2017-06-09 22:10:00+0000', tz='UTC'), Timestamp('2017-06-09 22:20:00+0000', tz='UTC'), Timestamp('2017-06-09 22:30:00+0000', tz='UTC'), Timestamp('2017-06-09 22:40:00+0000', tz='UTC'), Timestamp('2017-06-09 22:50:00+0000', tz='UTC'), Timestamp('2017-06-09 23:00:00+0000', tz='UTC'), Timestamp('2017-06-09 23:10:00+0000', tz='UTC'), Timestamp('2017-06-09 23:20:00+0000', tz='UTC'), Timestamp('2017-06-09 23:30:00+0000', tz='UTC'), Timestamp('2017-06-09 23:40:00+0000', tz='UTC'), Timestamp('2017-06-09 23:50:00+0000', tz='UTC'), Timestamp('2017-06-10 00:00:00+0000', tz='UTC'), Timestamp('2017-06-10 00:10:00+0000', tz='UTC'), Timestamp('2017-06-10 00:20:00+0000', tz='UTC'), Timestamp('2017-06-10 00:30:00+0000', tz='UTC'), Timestamp('2017-06-10 00:40:00+0000', tz='UTC'), Timestamp('2017-06-10 00:50:00+0000', tz='UTC'), Timestamp('2017-06-10 01:00:00+0000', tz='UTC'), Timestamp('2017-06-10 01:10:00+0000', tz='UTC'), Timestamp('2017-06-10 09:30:00+0000', tz='UTC'), Timestamp('2017-06-10 09:40:00+0000', tz='UTC'), Timestamp('2017-06-10 09:50:00+0000', tz='UTC'), Timestamp('2017-06-10 10:00:00+0000', tz='UTC'), Timestamp('2017-06-10 10:10:00+0000', tz='UTC'), Timestamp('2017-06-10 10:20:00+0000', tz='UTC'), Timestamp('2017-06-10 10:30:00+0000', tz='UTC'), Timestamp('2017-06-10 10:40:00+0000', tz='UTC'), Timestamp('2017-06-10 10:50:00+0000', tz='UTC'), Timestamp('2017-06-10 11:00:00+0000', tz='UTC'), Timestamp('2017-06-11 08:40:00+0000', tz='UTC'), Timestamp('2017-06-11 22:10:00+0000', tz='UTC'), Timestamp('2017-06-12 08:40:00+0000', tz='UTC'), Timestamp('2017-06-13 08:50:00+0000', tz='UTC'), Timestamp('2017-06-13 09:00:00+0000', tz='UTC'), Timestamp('2017-06-13 09:10:00+0000', tz='UTC'), Timestamp('2017-06-13 09:20:00+0000', tz='UTC'), Timestamp('2017-06-13 09:30:00+0000', tz='UTC'), Timestamp('2017-06-13 09:40:00+0000', tz='UTC'), Timestamp('2017-06-13 10:00:00+0000', tz='UTC'), Timestamp('2017-06-13 10:10:00+0000', tz='UTC'), Timestamp('2017-06-13 10:20:00+0000', tz='UTC'), Timestamp('2017-06-13 10:30:00+0000', tz='UTC'), Timestamp('2017-06-13 10:40:00+0000', tz='UTC'), Timestamp('2017-06-13 10:50:00+0000', tz='UTC'), Timestamp('2017-06-13 11:00:00+0000', tz='UTC'), Timestamp('2017-06-13 11:10:00+0000', tz='UTC'), Timestamp('2017-06-13 11:20:00+0000', tz='UTC'), Timestamp('2017-06-13 11:30:00+0000', tz='UTC'), Timestamp('2017-06-13 20:30:00+0000', tz='UTC'), Timestamp('2017-06-13 20:40:00+0000', tz='UTC'), Timestamp('2017-06-13 21:00:00+0000', tz='UTC'), Timestamp('2017-06-13 21:10:00+0000', tz='UTC'), Timestamp('2017-06-13 21:20:00+0000', tz='UTC'), Timestamp('2017-06-13 21:30:00+0000', tz='UTC'), Timestamp('2017-06-13 21:40:00+0000', tz='UTC'), Timestamp('2017-06-14 06:50:00+0000', tz='UTC'), Timestamp('2017-06-14 07:00:00+0000', tz='UTC'), Timestamp('2017-06-14 07:10:00+0000', tz='UTC'), Timestamp('2017-06-14 07:20:00+0000', tz='UTC'), Timestamp('2017-06-14 07:30:00+0000', tz='UTC'), Timestamp('2017-06-14 07:40:00+0000', tz='UTC'), Timestamp('2017-06-14 07:50:00+0000', tz='UTC'), Timestamp('2017-06-14 08:00:00+0000', tz='UTC'), Timestamp('2017-06-14 08:10:00+0000', tz='UTC'), Timestamp('2017-06-14 08:20:00+0000', tz='UTC'), Timestamp('2017-06-14 10:30:00+0000', tz='UTC'), Timestamp('2017-06-14 10:40:00+0000', tz='UTC'), Timestamp('2017-06-14 18:10:00+0000', tz='UTC'), Timestamp('2017-06-14 18:20:00+0000', tz='UTC'), Timestamp('2017-06-14 18:30:00+0000', tz='UTC'), Timestamp('2017-06-14 18:40:00+0000', tz='UTC'), Timestamp('2017-06-14 18:50:00+0000', tz='UTC'), Timestamp('2017-06-14 19:00:00+0000', tz='UTC'), Timestamp('2017-06-14 19:10:00+0000', tz='UTC'), Timestamp('2017-06-14 19:20:00+0000', tz='UTC'), Timestamp('2017-06-14 19:30:00+0000', tz='UTC'), Timestamp('2017-06-14 19:40:00+0000', tz='UTC'), Timestamp('2017-06-14 19:50:00+0000', tz='UTC'), Timestamp('2017-06-14 20:00:00+0000', tz='UTC'), Timestamp('2017-06-14 20:10:00+0000', tz='UTC'), Timestamp('2017-06-14 20:20:00+0000', tz='UTC'), Timestamp('2017-06-14 20:30:00+0000', tz='UTC'), Timestamp('2017-06-14 20:40:00+0000', tz='UTC'), Timestamp('2017-06-14 20:50:00+0000', tz='UTC'), Timestamp('2017-06-14 21:00:00+0000', tz='UTC'), Timestamp('2017-06-14 21:10:00+0000', tz='UTC'), Timestamp('2017-06-14 21:20:00+0000', tz='UTC'), Timestamp('2017-06-14 21:30:00+0000', tz='UTC'), Timestamp('2017-06-14 21:40:00+0000', tz='UTC'), Timestamp('2017-06-14 21:50:00+0000', tz='UTC'), Timestamp('2017-06-14 22:00:00+0000', tz='UTC'), Timestamp('2017-06-14 22:10:00+0000', tz='UTC'), Timestamp('2017-06-14 22:20:00+0000', tz='UTC'), Timestamp('2017-06-14 22:30:00+0000', tz='UTC'), Timestamp('2017-06-14 22:40:00+0000', tz='UTC'), Timestamp('2017-06-14 22:50:00+0000', tz='UTC'), Timestamp('2017-06-14 23:00:00+0000', tz='UTC'), Timestamp('2017-06-14 23:10:00+0000', tz='UTC'), Timestamp('2017-06-14 23:20:00+0000', tz='UTC'), Timestamp('2017-06-14 23:30:00+0000', tz='UTC'), Timestamp('2017-06-14 23:40:00+0000', tz='UTC'), Timestamp('2017-06-14 23:50:00+0000', tz='UTC')]

In [20]:
df_res.loc[df_res[29] == 1]
#df_res.loc[datetime.datetime(2017, 6, 7, 16)]

station,23,24,25,26,27,28,29,30,31,32,33,34,35,37
time,,,,,,,,,,,,,,
2017-06-07 01:40:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 01:50:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 02:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 02:10:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 02:20:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 02:30:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 02:40:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 02:50:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 03:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 03:10:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 03:20:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 03:30:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 03:40:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 03:50:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 04:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 04:10:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 04:20:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 04:30:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 04:40:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 04:50:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 05:00:00+00:00,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 05:10:00+00:00,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 05:20:00+00:00,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 05:30:00+00:00,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 05:40:00+00:00,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 05:50:00+00:00,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 06:00:00+00:00,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 06:10:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 06:20:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 06:30:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 06:40:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 06:50:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 07:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-07 07:10:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [114]:
df.loc[datetime.datetime(2017, 6, 10, 15, 40, tzinfo=pytz.utc)]

station
1    511.0
2    583.0
3    623.0
5    589.0
6    475.0
7     33.0
Name: 2017-06-10 15:40:00+00:00, dtype: float64

In [116]:
df.loc[datetime.datetime(2017, 6, 10, 15, 40, tzinfo=pytz.utc)].mean()

469.0

In [117]:
df.loc[datetime.datetime(2017, 6, 10, 15, 40, tzinfo=pytz.utc)].std()

220.45770569431227

In [6]:
df = (
    # A standard distribution
    pd.DataFrame({'nb': np.random.randint(0, 100, 20)})
        # Adding some outliers
        .append(pd.DataFrame({'nb': np.random.randint(100, 200, 2)}))
        # Reseting the index
        .reset_index(drop=True)
    )

In [7]:
df

     nb
0    71
1    28
2    12
3    94
4    25
5    60
6    72
7    46
8    76
9    32
10   66
11   26
12   20
13   97
14   72
15   18
16   17
17   49
18   29
19   75
20  110
21  164

In [41]:
Q1 = df[3].quantile(0.25)
Q3 = df[3].quantile(0.75)
IQR_1 = Q3 - Q1
df_q = pd.DataFrame(index=df[1].index)
print(Q1)
print(Q3)
print(IQR_1)

8.0
14.5
6.5

In [42]:
count = 0
for index, row in df[3].iteritems():
    if row < (Q1 - 1.5 * IQR_1) or row > (Q3 + 1.5 * IQR_1):
        count+=1
        df_q[index] = 1
print(count)

0