In [1]:
from vadetisweb.models import DataSet

In [2]:
dataset = DataSet.objects.get(id=25)

In [4]:
dataset.dataframe_class

ts_name,135,136,137,138,139,140,141,142,143,144
time,,,,,,,,,,
2019-01-01 00:00:00,False,False,False,False,False,False,False,False,False,False
2019-01-01 01:00:00,False,False,False,False,False,False,False,False,False,False
2019-01-01 02:00:00,False,False,False,False,False,False,False,False,False,False
2019-01-01 03:00:00,False,False,False,False,False,False,False,False,False,False
2019-01-01 04:00:00,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
2019-12-31 19:00:00,False,False,False,False,False,False,False,False,False,False
2019-12-31 20:00:00,False,False,False,False,False,False,False,False,False,False
2019-12-31 21:00:00,False,False,False,False,False,False,False,False,False,False
2019-12-31 22:00:00,False,False,False,False,False,False,False,False,False,False
2019-12-31 23:00:00,False,False,False,False,False,False,False,False,False,False