In [107]:
import pandas as pd
import numpy as np
from lisa.models import DataSet
from datetime import datetime

In [54]:
ds = DataSet.objects.get(id=43)
ds.dataframe_class

time_series                  113    114    115    116    117    118    119
time
2017-07-01 00:00:00+00:00  False  False  False  False  False  False  False
2017-07-01 00:10:00+00:00  False  False  False  False  False  False  False
2017-07-01 00:20:00+00:00  False  False  False  False  False  False  False
2017-07-01 00:30:00+00:00  False  False  False  False  False  False  False
2017-07-01 00:40:00+00:00  False  False  False  False  False  False  False
2017-07-01 00:50:00+00:00  False  False  False  False  False  False  False
2017-07-01 01:00:00+00:00  False  False  False  False  False  False  False
2017-07-01 01:10:00+00:00  False  False  False  False  False  False  False
2017-07-01 01:20:00+00:00  False  False  False   True  False  False  False
2017-07-01 01:30:00+00:00  False  False  False  False  False  False  False
2017-07-01 01:40:00+00:00  False  False  False  False  False  False  False
2017-07-01 01:50:00+00:00  False  False  False  False  False  False  False
2017-07-01 02:00:00+00:00  False  False  False  False  False  False  False
2017-07-01 02:10:00+00:00  False  False  False  False  False  False  False
2017-07-01 02:20:00+00:00  False  False  False  False  False  False  False
2017-07-01 02:30:00+00:00  False  False  False  False  False  False  False
2017-07-01 02:40:00+00:00  False  False  False  False  False  False  False
2017-07-01 02:50:00+00:00  False  False  False  False  False  False  False
2017-07-01 03:00:00+00:00  False  False  False  False  False  False  False
2017-07-01 03:10:00+00:00  False  False  False  False  False  False  False
2017-07-01 03:20:00+00:00  False  False  False  False  False  False  False
2017-07-01 03:30:00+00:00  False  False  False  False  False  False  False
2017-07-01 03:40:00+00:00  False  False  False  False  False  False  False
2017-07-01 03:50:00+00:00  False  False  False  False  False  False  False
2017-07-01 04:00:00+00:00  False  False  False  False  False  False  False
2017-07-01 04:10:00+00:00  False  False  False  False  False  False  False
2017-07-01 04:20:00+00:00  False  False  False  False  False  False  False
2017-07-01 04:30:00+00:00  False  False  False  False  False  False  False
2017-07-01 04:40:00+00:00  False  False  False  False  False  False  False
2017-07-01 04:50:00+00:00  False  False  False  False  False  False  False
...                          ...    ...    ...    ...    ...    ...    ...
2017-07-14 16:20:00+00:00  False  False  False  False  False  False  False
2017-07-14 16:30:00+00:00  False  False  False  False  False  False  False
2017-07-14 16:40:00+00:00  False  False  False  False  False  False  False
2017-07-14 16:50:00+00:00  False  False  False  False   True  False  False
2017-07-14 17:00:00+00:00  False  False  False  False  False  False  False
2017-07-14 17:10:00+00:00  False  False  False  False  False  False  False
2017-07-14 17:20:00+00:00  False  False  False  False  False  False  False
2017-07-14 17:30:00+00:00  False  False  False  False  False  False  False
2017-07-14 17:40:00+00:00  False  False  False  False  False  False  False
2017-07-14 17:50:00+00:00  False  False  False  False  False  False  False
2017-07-14 18:00:00+00:00  False  False  False  False  False  False  False
2017-07-14 18:10:00+00:00  False  False  False  False  False  False  False
2017-07-14 18:20:00+00:00  False  False  False  False  False  False  False
2017-07-14 18:30:00+00:00  False  False  False  False  False  False  False
2017-07-14 18:40:00+00:00  False  False  False  False  False  False  False
2017-07-14 18:50:00+00:00  False  False  False  False  False  False  False
2017-07-14 19:00:00+00:00  False  False  False  False  False  False  False
2017-07-14 19:10:00+00:00  False  False  False  False  False  False  False
2017-07-14 19:20:00+00:00  False  False  False  False  False  False  False
2017-07-14 19:30:00+00:00  False  False  False  False  False  False  False
2017-07-14 19:40:00+00:00  False  False  False  False  False  False  False
2017-07-14 19:50:00+00:00  False  False  False  False  False  False  False
2017-07-14 20:00:00+00:00  False  False  False  False  False  False  False
2017-07-14 20:10:00+00:00  False  False  False  False  False  False  False
2017-07-14 20:20:00+00:00  False  False  False  False  False  False  False
2017-07-14 20:30:00+00:00  False  False  False  False  False  False  False
2017-07-14 20:40:00+00:00  False  False  False  False  False  False  False
2017-07-14 20:50:00+00:00  False  False  False  False  False  False  False
2017-07-14 21:00:00+00:00  False  False  False  False  False  False  False
2017-07-14 21:10:00+00:00  False  False  False  False  False  False  False

[2000 rows x 7 columns]

In [178]:
with open('/Users/adrian/Uni/MasterThesis/test_data/test_data_gaussian/gaussian_01.txt', 'r') as file_csv:

    df_read = pd.read_csv(file_csv, 
                sep=';',
                index_col='time',
                parse_dates=True)
    #print(df_read)

group_by_ts_name = df_read.groupby('ts_name')
df_ts_unit = group_by_ts_name.apply(lambda x: x['unit'].unique())
df_ts_unit.index.tolist()    
#group_by_index = df_read.groupby(level=0)
#group_by_index.apply(lambda x: x['ts_name'].duplicated()).any()

#df_read.loc['2017-07-01 00:20:00']

#df_read.groupby('ts_name').filter(lambda x: len(x) > 1)[df_read.index.duplicated()]
#df_read.groupby(df_read.index)['ts_name'].filter(lambda x: len(x) > 1)['ts_name']
#df_read.groupby(df_read.index)['ts_name'].apply(lambda x: x['ts_name'].unique())
#df_read.groupby(level=0).filter(lambda x: len(x) > 1)[df_read.index]

['Series_0',
 'Series_1',
 'Series_2',
 'Series_3',
 'Series_4',
 'Series_5',
 'Series_6',
 'Series_7',
 'Series_8',
 'Series_9']

In [106]:
group_by_ts_name = df_read.groupby('ts_name')
df_ts_unit = group_by_ts_name.apply(lambda x: x['unit'].unique())

print(df_ts_unit)

ts_name
Series_0    [Quantity]
dtype: object

In [118]:
df = df_read.pivot(columns='ts_name', values='value')
print(df)

ValueError: Index contains duplicate entries, cannot reshape

In [58]:
df = df_read.pivot(columns='ts_name', values='class')
df = df.applymap(lambda x: True if x == 1 else False)
df.count().sum()

20000

In [19]:
df.index = df.index.tz_localize('UTC')
df = df.rename(columns={'Series_0': 10})

In [49]:
df = df.rename(columns={'Series_0': 10})

In [50]:
df

ts_name,10,Series_1,Series_2,Series_3,Series_4,Series_5,Series_6,Series_7,Series_8,Series_9
time,,,,,,,,,,
2017-07-01 00:00:00,0.605940,0.906242,0.004591,-0.416274,0.278499,0.559137,1.349555,5.949489,0.957354,1.872816
2017-07-01 00:10:00,0.527723,0.930549,3.736135,1.373810,0.551740,0.529262,1.897311,2.848954,0.871742,3.174150
2017-07-01 00:20:00,2.902003,0.431831,0.864320,0.728954,0.028580,1.084620,1.474360,1.873849,1.281134,1.943666
2017-07-01 00:30:00,1.363739,1.607502,1.432026,-0.064481,-0.193002,0.797147,1.934674,2.549719,1.197316,1.683636
2017-07-01 00:40:00,-0.531530,1.957308,1.372882,-0.073446,0.792659,2.834468,1.595870,3.641457,1.361100,0.470531
2017-07-01 00:50:00,2.004597,0.367599,1.065225,4.097343,1.303569,2.610154,1.233858,4.063859,0.190378,1.988092
2017-07-01 01:00:00,2.520786,4.214960,1.080852,1.598830,1.062125,1.438689,1.646913,0.525006,2.977596,2.725506
2017-07-01 01:10:00,2.006061,1.685254,1.438750,0.382022,-0.311206,0.336821,2.792419,1.860916,-0.679269,2.865448
2017-07-01 01:20:00,0.922162,1.485918,1.456416,0.267636,0.516034,2.253972,2.063719,2.454616,2.925559,1.319932
2017-07-01 01:30:00,1.883773,1.882311,-0.491424,1.406671,2.288843,1.534025,2.961269,2.835048,0.889238,2.460840
2017-07-01 01:40:00,1.170637,-0.050690,-0.185851,1.544142,1.409517,-0.390594,1.541591,1.542884,2.431023,0.039076
2017-07-01 01:50:00,0.681692,0.590239,2.122983,3.248574,-1.173711,1.037230,0.958030,0.671544,3.347987,2.665828
2017-07-01 02:00:00,1.148032,0.452954,-0.188705,1.144330,0.596615,1.297827,2.073707,0.782553,1.220280,2.527227
2017-07-01 02:10:00,3.475337,2.827501,1.663367,0.195354,1.232245,1.297222,1.320119,1.000768,3.025351,2.966078
2017-07-01 02:20:00,0.012029,0.914811,0.926210,1.330625,2.351947,2.683406,1.012768,1.453030,2.259660,0.008454
2017-07-01 02:30:00,2.141876,1.906387,0.035358,1.324288,1.814525,0.921174,2.645198,2.085090,2.277318,3.162863
2017-07-01 02:40:00,-0.227908,-0.194596,-0.194038,1.204197,2.770593,3.370777,2.580696,-0.032621,2.879460,1.798241
2017-07-01 02:50:00,0.332400,1.462912,0.382116,0.532488,-0.623804,0.453652,-0.296811,0.943915,1.312359,1.812499
2017-07-01 03:00:00,2.669237,1.348976,0.079167,0.860294,1.419649,2.420992,1.757137,2.357316,1.610109,3.618864
2017-07-01 03:10:00,0.466657,1.991152,1.931797,0.034230,2.537622,1.266486,2.962815,1.742640,3.609204,1.639779
2017-07-01 03:20:00,1.284277,0.123477,2.558372,2.701945,1.355292,1.372160,0.949507,0.857895,3.248857,-0.050848
2017-07-01 03:30:00,0.803351,0.385852,1.501605,-0.167655,0.367564,1.697617,1.614350,1.958005,-0.904165,2.075860
2017-07-01 03:40:00,1.440199,3.228648,0.985315,1.548534,0.094679,1.071067,0.681480,2.388496,0.776962,3.884591
2017-07-01 03:50:00,0.214990,0.655732,0.109350,3.556290,0.379540,0.939307,0.461732,0.889734,1.811688,4.449571
2017-07-01 04:00:00,0.614353,1.026386,3.245533,2.842120,1.951092,0.826406,3.389212,2.354130,1.424149,3.955735
2017-07-01 04:10:00,2.456104,1.400029,2.561463,0.195814,2.467716,2.144940,3.264192,0.251943,2.294010,0.913788
2017-07-01 04:20:00,-0.179186,1.479253,2.798700,0.346849,1.563794,1.361454,1.388206,2.938483,0.894495,1.848271
2017-07-01 04:30:00,0.819629,0.937328,3.024671,1.212788,0.478634,0.988781,1.216915,2.680832,2.770845,1.708894
2017-07-01 04:40:00,1.992577,1.987060,0.786899,2.019395,1.334208,0.568293,1.878753,2.867587,1.013016,2.344401
2017-07-01 04:50:00,1.729195,0.630404,3.032717,3.226752,1.632118,2.530375,1.382134,2.416981,2.213889,1.713120
...,...,...,...,...,...,...,...,...,...,...
2017-07-14 16:20:00,1.238641,2.043873,3.004722,2.200831,0.587495,3.487070,1.217779,1.227895,2.219400,1.096309
2017-07-14 16:30:00,-0.243748,-0.086182,1.395293,0.463196,1.576662,0.237261,2.057373,2.003026,2.953090,1.431425
2017-07-14 16:40:00,-0.280628,0.457279,-0.272848,2.405973,2.138059,1.427279,1.906142,1.254479,0.595610,1.154489
2017-07-14 16:50:00,1.661037,1.853020,2.072933,1.851346,1.720623,1.041577,2.155256,2.544166,1.436514,1.764929
2017-07-14 17:00:00,1.069116,0.151053,2.572072,0.674809,2.696492,1.761787,2.398581,2.719783,1.050307,1.497560
2017-07-14 17:10:00,-0.405557,1.886694,0.581530,1.724658,1.906704,1.080052,1.668891,0.961078,1.974915,1.908001
2017-07-14 17:20:00,1.413005,-0.698999,1.977515,0.893718,-1.904448,2.665452,1.138116,1.234166,2.793159,0.602329
2017-07-14 17:30:00,1.656305,1.589438,1.663858,0.176676,1.823181,2.085835,0.888853,1.377678,1.256785,3.354714
2017-07-14 17:40:00,1.394049,-0.289266,0.240229,0.568110,0.771069,2.190065,2.585748,1.063882,0.938292,2.647604
2017-07-14 17:50:00,1.492845,1.494723,-4.247704,2.394919,3.466402,1.710079,3.953067,0.849883,1.100912,0.408904
2017-07-14 18:00:00,0.585436,0.483530,0.656785,2.031266,3.349937,1.381754,-0.229107,1.842993,2.143192,0.633275
2017-07-14 18:10:00,0.892542,2.472964,2.714573,1.442427,3.474499,1.735649,-0.331171,1.078261,0.886761,2.582575
2017-07-14 18:20:00,1.554355,0.023773,0.097994,1.304383,0.540947,3.116759,3.113616,1.582141,-0.752672,-0.058531
2017-07-14 18:30:00,1.153495,0.518096,0.227475,1.754270,1.088657,2.185498,0.919775,1.592585,1.102109,1.527929
2017-07-14 18:40:00,1.553809,1.403817,1.650320,1.090857,1.601818,1.147154,1.172222,0.884606,2.171381,0.719700
2017-07-14 18:50:00,2.280110,2.099160,1.161894,3.068123,1.174157,2.698982,0.449193,0.392394,2.538921,1.752989
2017-07-14 19:00:00,-0.187861,1.375925,0.606309,2.510259,0.230859,1.438748,2.639251,3.908774,3.101232,0.409708
2017-07-14 19:10:00,1.182539,0.240454,2.703075,2.062403,0.602996,1.849384,1.883940,2.129072,2.023119,0.949516
2017-07-14 19:20:00,2.218495,2.995637,1.937199,3.805826,1.510360,-0.162907,1.910562,1.226866,1.799859,2.869790
2017-07-14 19:30:00,0.077889,2.705324,0.596539,3.291603,1.438077,2.283073,-0.342789,1.764800,2.074744,2.409314
2017-07-14 19:40:00,4.681423,1.196267,1.539552,0.310760,1.190805,2.171931,2.204122,2.512307,5.925509,2.354642
2017-07-14 19:50:00,0.421065,-0.332058,3.569218,2.071983,0.633455,0.441814,0.127839,2.453395,1.819629,1.688885
2017-07-14 20:00:00,0.246935,2.970409,0.986515,1.744901,2.168078,1.776178,2.642011,2.857836,1.283097,2.844868
2017-07-14 20:10:00,1.403301,5.651155,1.452951,1.743029,2.032099,1.588734,1.711076,0.338781,1.518092,2.684429
2017-07-14 20:20:00,0.234506,0.441506,1.184591,0.532705,0.928514,0.365498,1.943162,1.516944,0.280128,1.899808
2017-07-14 20:30:00,1.744090,0.370166,2.078572,1.365354,3.197180,0.812487,4.037107,2.058871,1.342986,4.043923
2017-07-14 20:40:00,0.644793,0.030020,1.419130,1.758003,0.780159,1.308216,5.216987,2.227047,1.324671,2.135901
2017-07-14 20:50:00,0.187223,-0.582574,1.997053,1.702479,0.418219,2.217387,5.583336,1.286608,0.827940,1.839846
2017-07-14 21:00:00,1.189279,1.795809,2.053468,1.274045,0.325316,0.771391,1.445393,1.439473,2.265433,1.391227
2017-07-14 21:10:00,2.895627,2.226851,1.451983,-0.281116,1.789125,0.315682,1.016937,3.626791,2.500317,0.682202

In [96]:
with open('/Users/adrian/Uni/MasterThesis/test_data/test_data_gaussian_geo/gaussian_geo_01_locations.txt', 'r') as locations_csv:

    df_loc = pd.read_csv(locations_csv,
                         sep=';',
                         index_col='ts_name')
    print(df_loc)
    for index, row in df_loc.items():
        print(index)
        print(row)
print(df_loc.loc[ts_indexes])

            l_name       lon        lat  ch1903_e  ch1903_n  height
ts_name
Series_1     Aigle  6.916667  46.333333    560400    130713     381
Series_2   Begnins  6.266667  46.450000    509460    144415     582
Series_3  Burtigny  6.266667  46.466667    510200    146080     732
Series_4  Changins  6.233333  46.400000    507130    139310     440
Series_5   Dezaley  6.766667  46.483333    548470    147690     420
Series_6      Etoy  6.416667  46.483333    521720    148080     424
Series_7   Payerne  6.950000  46.816667    562127    184612     490
l_name
ts_name
Series_1       Aigle
Series_2     Begnins
Series_3    Burtigny
Series_4    Changins
Series_5     Dezaley
Series_6        Etoy
Series_7     Payerne
Name: l_name, dtype: object
lon
ts_name
Series_1    6.916667
Series_2    6.266667
Series_3    6.266667
Series_4    6.233333
Series_5    6.766667
Series_6    6.416667
Series_7    6.950000
Name: lon, dtype: float64
lat
ts_name
Series_1    46.333333
Series_2    46.450000
Series_3    46.466667
Series_4    46.400000
Series_5    46.483333
Series_6    46.483333
Series_7    46.816667
Name: lat, dtype: float64
ch1903_e
ts_name
Series_1    560400
Series_2    509460
Series_3    510200
Series_4    507130
Series_5    548470
Series_6    521720
Series_7    562127
Name: ch1903_e, dtype: int64
ch1903_n
ts_name
Series_1    130713
Series_2    144415
Series_3    146080
Series_4    139310
Series_5    147690
Series_6    148080
Series_7    184612
Name: ch1903_n, dtype: int64
height
ts_name
Series_1    381
Series_2    582
Series_3    732
Series_4    440
Series_5    420
Series_6    424
Series_7    490
Name: height, dtype: int64
            l_name       lon        lat  ch1903_e  ch1903_n  height
ts_name
Series_1     Aigle  6.916667  46.333333    560400    130713     381
Series_2   Begnins  6.266667  46.450000    509460    144415     582
Series_3  Burtigny  6.266667  46.466667    510200    146080     732
Series_4  Changins  6.233333  46.400000    507130    139310     440
Series_5   Dezaley  6.766667  46.483333    548470    147690     420

In [94]:

# check if locations for all series are provided
ts_indexes = ['Series_1', 'Series_2', 'Series_3', 'Series_4', 'Series_5']
print(df_loc[~df_loc.index.isin(ts_indexes)].index.values)
print(df_loc.index.isin(ts_indexes))

if not np.all(df_loc.index.isin(ts_indexes) == True):
    df_loc[~df_loc.index.isin(ts_indexes)]
    err_msg = "Some time series are missing: %s " % ', '.join(str(x) for x in df_loc[~df_loc.index.isin(ts_indexes)].index.values)
    raise ValueError(err_msg)

['Series_6' 'Series_7']
[ True  True  True  True  True False False]

ValueError: Some time series are missing: Series_6, Series_7

In [104]:
df_loc.loc[ts_indexes, pd.Series(['l_name', 'lon', 'lat', 'height'])]

            l_name       lon        lat  height
ts_name
Series_1     Aigle  6.916667  46.333333     381
Series_2   Begnins  6.266667  46.450000     582
Series_3  Burtigny  6.266667  46.466667     732
Series_4  Changins  6.233333  46.400000     440
Series_5   Dezaley  6.766667  46.483333     420